// Code generated by mockery v2.38.0. DO NOT EDIT.

package mock

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	model "github.com/v-starostin/gophermart/internal/model"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields: login, password
func (_m *Service) Authenticate(login string, password string) (string, error) {
	ret := _m.Called(login, password)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(login, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(login, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(login, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBalance provides a mock function with given fields: userID
func (_m *Service) GetBalance(userID uuid.UUID) (float64, float64, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 float64
	var r1 float64
	var r2 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (float64, float64, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) float64); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) float64); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Get(1).(float64)
	}

	if rf, ok := ret.Get(2).(func(uuid.UUID) error); ok {
		r2 = rf(userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetOrders provides a mock function with given fields: userID
func (_m *Service) GetOrders(userID uuid.UUID) ([]model.Order, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrders")
	}

	var r0 []model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]model.Order, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []model.Order); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWithdrawals provides a mock function with given fields: userID
func (_m *Service) GetWithdrawals(userID uuid.UUID) ([]model.Withdrawal, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWithdrawals")
	}

	var r0 []model.Withdrawal
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]model.Withdrawal, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []model.Withdrawal); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Withdrawal)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterUser provides a mock function with given fields: login, password
func (_m *Service) RegisterUser(login string, password string) error {
	ret := _m.Called(login, password)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(login, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadOrder provides a mock function with given fields: userID, orderNumber
func (_m *Service) UploadOrder(userID uuid.UUID, orderNumber string) error {
	ret := _m.Called(userID, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for UploadOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) error); ok {
		r0 = rf(userID, orderNumber)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithdrawalRequest provides a mock function with given fields: userID, orderNumber, sum
func (_m *Service) WithdrawalRequest(userID uuid.UUID, orderNumber string, sum float64) error {
	ret := _m.Called(userID, orderNumber, sum)

	if len(ret) == 0 {
		panic("no return value specified for WithdrawalRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, float64) error); ok {
		r0 = rf(userID, orderNumber, sum)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
