// Code generated by mockery v2.38.0. DO NOT EDIT.

package mock

import (
	mock "github.com/stretchr/testify/mock"
	model "github.com/v-starostin/gophermart/internal/model"

	uuid "github.com/google/uuid"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// AddOrder provides a mock function with given fields: userID, order
func (_m *Storage) AddOrder(userID uuid.UUID, order model.Order) error {
	ret := _m.Called(userID, order)

	if len(ret) == 0 {
		panic("no return value specified for AddOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, model.Order) error); ok {
		r0 = rf(userID, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddUser provides a mock function with given fields: login, password
func (_m *Storage) AddUser(login string, password string) error {
	ret := _m.Called(login, password)

	if len(ret) == 0 {
		panic("no return value specified for AddUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(login, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBalance provides a mock function with given fields: _a0
func (_m *Storage) GetBalance(_a0 uuid.UUID) (float64, float64, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 float64
	var r1 float64
	var r2 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (float64, float64, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) float64); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) float64); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Get(1).(float64)
	}

	if rf, ok := ret.Get(2).(func(uuid.UUID) error); ok {
		r2 = rf(_a0)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetOrder provides a mock function with given fields: userID, orderNumber
func (_m *Storage) GetOrder(userID uuid.UUID, orderNumber string) (*model.Order, error) {
	ret := _m.Called(userID, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) (*model.Order, error)); ok {
		return rf(userID, orderNumber)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) *model.Order); ok {
		r0 = rf(userID, orderNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, string) error); ok {
		r1 = rf(userID, orderNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrders provides a mock function with given fields: userID
func (_m *Storage) GetOrders(userID uuid.UUID) ([]model.Order, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrders")
	}

	var r0 []model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]model.Order, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []model.Order); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: login, password
func (_m *Storage) GetUser(login string, password string) (*model.User, error) {
	ret := _m.Called(login, password)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*model.User, error)); ok {
		return rf(login, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) *model.User); ok {
		r0 = rf(login, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(login, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWithdrawals provides a mock function with given fields: userID
func (_m *Storage) GetWithdrawals(userID uuid.UUID) ([]model.Withdrawal, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWithdrawals")
	}

	var r0 []model.Withdrawal
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]model.Withdrawal, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []model.Withdrawal); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Withdrawal)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WithdrawalRequest provides a mock function with given fields: userID, orderNumber, sum
func (_m *Storage) WithdrawalRequest(userID uuid.UUID, orderNumber string, sum float64) error {
	ret := _m.Called(userID, orderNumber, sum)

	if len(ret) == 0 {
		panic("no return value specified for WithdrawalRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, float64) error); ok {
		r0 = rf(userID, orderNumber, sum)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
